version: "3.7"
services:
  ec-ssr:
    image: registry.cn-shanghai.aliyuncs.com/helix-prod/ec-ssr:3.42
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "2"
          memory: 4096M
    ports:
      - "3000:3000"
    networks:
      - net
    volumes:
      - 
networks:
  net:
